config/routes.rb
Rails.application.routes.draw do
  resources :timelines
  resources :tags
  get 'users/show'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  resources :articles do
    resources :comments
  end

  get 'home/index'

  root 'home#index'

  get '/:id' => 'users#show', as: 'profile'
  get '/:id/follow' => 'users#follow', as: 'follow'
  get '/:id/unfollow' => 'users#unfollow', as: 'unfollow'

  get '/articles/:article_id/comments/:id/vote_up' => 'comments#vote_up', as: 'vote_up_comment'
  get '/articles/:article_id/comments/:id/vote_down' => 'comments#vote_down', as: 'vote_down_comment'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  include PublicActivity::Model
  tracked owner: :current_user

  friendly_id :title, use: :slugged
  cattr_accessor :current_user, :timeline

  belongs_to :user
  has_many :comments

  has_many :tags, :through => :article_taggable
  has_many :timelines, :through => :timeline_map

  has_many :article_taggables
  has_many :timeline_maps
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:user_id, :timeline_uid, :title, :summary, :slug)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :timeline %><br>
    <%= f.text_field :timeline %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.user %></td>
        <td><%= article.title %></td>
        <td><%= article.summary %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @article.summary %>
</p>

<h3>Comments</h3>

<ul>
	<% @article.comments.each do |comment| %>
		<li><%= comment.user.alias %>: <%= comment.comment %> (<%= Integer(comment.reputation_for(:votes)) %>) - <%= link_to "Up", vote_up_comment_path(@article, comment), :remote => true %>/<%= link_to "Down", vote_down_comment_path(@article, comment), :remote => true %></li>
	<% end %>
</ul>

<%= form_for([@article, @article.comments.build], html: { class: "form-horizontal" }) do |f| %>

	<div class="control-group">
		<%= f.label :comment, class: "control-label" %>
		<div class="controls">
			<%= f.text_area :comment %>
		</div>
	</div>

	

	<div class="control-group">
		<div class="controls">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
		
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>