config/routes.rb
Rails.application.routes.draw do
  resources :timelines
  resources :tags
  get 'users/show'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  resources :articles do
    resources :comments
  end

  get 'home/index'

  root 'home#index'

  get '/:id' => 'users#show', as: 'profile'
  get '/:id/follow' => 'users#follow', as: 'follow'
  get '/:id/unfollow' => 'users#unfollow', as: 'unfollow'

  get '/articles/:article_id/comments/:id/vote_up' => 'comments#vote_up', as: 'vote_up_comment'
  get '/articles/:article_id/comments/:id/vote_down' => 'comments#vote_down', as: 'vote_down_comment'
  

end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  include PublicActivity::Model
  
  acts_as_followable
  
  cattr_accessor :current_user
  has_many :articles, :through => :timeline_map
  has_many :timeline_maps

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :set_timeline, only: [:show, :edit, :update, :destroy]

  # GET /timelines
  # GET /timelines.json
  def index
    @timelines = Timeline.all
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
  end

  # GET /timelines/new
  def new
    @timeline = Timeline.new
  end

  # GET /timelines/1/edit
  def edit
  end

  # POST /timelines
  # POST /timelines.json
  def create
    @timeline = Timeline.new(timeline_params)

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @timeline, notice: 'Timeline was successfully created.' }
        format.json { render :show, status: :created, location: @timeline }
      else
        format.html { render :new }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timelines/1
  # PATCH/PUT /timelines/1.json
  def update
    respond_to do |format|
      if @timeline.update(timeline_params)
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeline }
      else
        format.html { render :edit }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelines/1
  # DELETE /timelines/1.json
  def destroy
    @timeline.destroy
    respond_to do |format|
      format.html { redirect_to timelines_url, notice: 'Timeline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeline
      @timeline = Timeline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeline_params
      params.require(:timeline).permit(:name)
    end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_form.html.erb
<%= form_for(@timeline) do |f| %>
  <% if @timeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeline.errors.count, "error") %> prohibited this timeline from being saved:</h2>

      <ul>
      <% @timeline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timelines/edit.html.erb
<h1>Editing Timeline</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeline %> |
<%= link_to 'Back', timelines_path %>

app/views/timelines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Timelines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timelines.each do |timeline| %>
      <tr>
        <td><%= timeline.name %></td>
        <td><%= link_to 'Show', timeline %></td>
        <td><%= link_to 'Edit', edit_timeline_path(timeline) %></td>
        <td><%= link_to 'Destroy', timeline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeline', new_timeline_path %>

app/views/timelines/new.html.erb
<h1>New Timeline</h1>

<%= render 'form' %>

<%= link_to 'Back', timelines_path %>

app/views/timelines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @timeline.name %>
</p>

<%= link_to 'Edit', edit_timeline_path(@timeline) %> |
<%= link_to 'Back', timelines_path %>